apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - backend-deployment.yaml
 - backend-service.yaml
 - db-deployment.yaml
 - db-data-persistentvolumeclaim.yaml
 - db-password-secret.yaml
 - db-service.yaml

#patchesStrategicMerge:
#  - despliegue.yaml

images:
  - name: tyler0128/spring
    newTag:  "333"